In [1]:
# Task 1
# House Price Prediction using Linear Regression

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Sample dataset
data = {
    'Area': [800, 1000, 1200, 1500, 1800],
    'Rooms': [2, 2, 3, 3, 4],
    'Price': [40, 50, 60, 75, 90]   # price in lakhs
}

df = pd.DataFrame(data)

# Features and target
X = df[['Area', 'Rooms']]
y = df['Price']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Train model
model = LinearRegression()
model.fit(X_train, y_train)

# Prediction
predicted_price = model.predict([[1400, 3]])

print("Predicted House Price (in lakhs):", predicted_price[0])


Predicted House Price (in lakhs): 70.0


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [3]:
#Task 2
import numpy as np

# Input matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# Addition
print("\nAddition:\n", A + B)

# Subtraction
print("\nSubtraction:\n", A - B)

# Multiplication
print("\nMultiplication:\n", np.dot(A, B))

# Transpose
print("\nTranspose of A:\n", A.T)

# Determinant
print("\nDeterminant of A:", np.linalg.det(A))


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]

Addition:
 [[ 6  8]
 [10 12]]

Subtraction:
 [[-4 -4]
 [-4 -4]]

Multiplication:
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]

Determinant of A: -2.0000000000000004
